
// This file is generated by drogon_ctl

#include "./ticket.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::bug_tracker;

const std::string Ticket::Cols::_id = "id";
const std::string Ticket::Cols::_title = "title";
const std::string Ticket::Cols::_descr = "descr";
const std::string Ticket::Cols::_ticket_status = "ticket_status";
const std::string Ticket::Cols::_severity = "severity";
const std::string Ticket::Cols::_created_date = "created_date";
const std::string Ticket::Cols::_resolved_date = "resolved_date";
const std::string Ticket::Cols::_assigned = "assigned";
const std::string Ticket::Cols::_project = "project";
const std::string Ticket::primaryKeyName = "id";
const bool Ticket::hasPrimaryKey = true;
const std::string Ticket::tableName = "ticket";

const std::vector<typename Ticket::MetaData> Ticket::metaData_={
    {"id", "int32_t", "integer", 4, true, true, true},
    {"title", "std::string", "text", 0, false, false, true},
    {"descr", "std::string", "text", 0, false, false, true},
    {"ticket_status", "std::string", "USER-DEFINED", 0, false, false, true},
    {"severity", "std::string", "USER-DEFINED", 0, false, false, true},
    {"created_date", "trantor::Date", "timestamp without time zone", 0, false, false, true},
    {"resolved_date", "trantor::Date", "timestamp without time zone", 0, false, false, false},
    {"assigned", "int32_t", "integer", 4, false, false, false},
    {"project", "int32_t", "integer", 4, false, false, true}
};
const std::string& Ticket::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size() );
    return metaData_[index].colName_;
}

Ticket::Ticket(const Row& r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0) {
        if(!r["id"].isNull() )
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>() );
        if(!r["title"].isNull() )
            title_=std::make_shared<std::string>(r["title"].as<std::string>() );
        if(!r["descr"].isNull() )
            descr_=std::make_shared<std::string>(r["descr"].as<std::string>() );
        if(!r["ticket_status"].isNull() )
            ticketStatus_=std::make_shared<std::string>(r["ticket_status"].as<std::string>() );
        if(!r["severity"].isNull() )
            severity_=std::make_shared<std::string>(r["severity"].as<std::string>() );
        if(!r["created_date"].isNull() ) {
            auto timeStr = r["created_date"].as<std::string>();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["resolved_date"].isNull() ) {
            auto timeStr = r["resolved_date"].as<std::string>();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["assigned"].isNull() )
            assigned_=std::make_shared<int32_t>(r["assigned"].as<int32_t>() );
        if(!r["project"].isNull() )
            project_=std::make_shared<int32_t>(r["project"].as<int32_t>() );
    } else {
        size_t offset = static_cast<size_t>(indexOffset);
        if(offset + 9 > r.size() ) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull() )
            id_=std::make_shared<int32_t>(r[index].as<int32_t>() );
        index = offset + 1;
        if(!r[index].isNull() )
            title_=std::make_shared<std::string>(r[index].as<std::string>() );
        index = offset + 2;
        if(!r[index].isNull() )
            descr_=std::make_shared<std::string>(r[index].as<std::string>() );
        index = offset + 3;
        if(!r[index].isNull() )
            ticketStatus_=std::make_shared<std::string>(r[index].as<std::string>() );
        index = offset + 4;
        if(!r[index].isNull() )
            severity_=std::make_shared<std::string>(r[index].as<std::string>() );
        index = offset + 5;
        if(!r[index].isNull() ) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull() ) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull() )
            assigned_=std::make_shared<int32_t>(r[index].as<int32_t>() );
        index = offset + 8;
        if(!r[index].isNull() )
            project_=std::make_shared<int32_t>(r[index].as<int32_t>() );
    }
}

Ticket::Ticket(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]) ) {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull() )
            id_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[0]].asInt64() ) );
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]) ) {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull() )
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString() );
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]) ) {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull() )
            descr_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString() );
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]) ) {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull() )
            ticketStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString() );
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]) ) {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull() )
            severity_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString() );
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]) ) {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull() ) {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]) ) {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull() ) {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]) ) {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull() )
            assigned_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[7]].asInt64() ) );
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]) ) {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull() )
            project_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[8]].asInt64() ) );
    }
}

Ticket::Ticket(const Json::Value& pJson) noexcept(false)
{
    if(pJson.isMember("id") ) {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull() )
            id_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["id"].asInt64() ) );
    }
    if(pJson.isMember("title") ) {
        dirtyFlag_[1]=true;
        if(!pJson["title"].isNull() )
            title_=std::make_shared<std::string>(pJson["title"].asString() );
    }
    if(pJson.isMember("descr") ) {
        dirtyFlag_[2]=true;
        if(!pJson["descr"].isNull() )
            descr_=std::make_shared<std::string>(pJson["descr"].asString() );
    }
    if(pJson.isMember("ticket_status") ) {
        dirtyFlag_[3]=true;
        if(!pJson["ticket_status"].isNull() )
            ticketStatus_=std::make_shared<std::string>(pJson["ticket_status"].asString() );
    }
    if(pJson.isMember("severity") ) {
        dirtyFlag_[4]=true;
        if(!pJson["severity"].isNull() )
            severity_=std::make_shared<std::string>(pJson["severity"].asString() );
    }
    if(pJson.isMember("created_date") ) {
        dirtyFlag_[5]=true;
        if(!pJson["created_date"].isNull() ) {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("resolved_date") ) {
        dirtyFlag_[6]=true;
        if(!pJson["resolved_date"].isNull() ) {
            auto timeStr = pJson["resolved_date"].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("assigned") ) {
        dirtyFlag_[7]=true;
        if(!pJson["assigned"].isNull() )
            assigned_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["assigned"].asInt64() ) );
    }
    if(pJson.isMember("project") ) {
        dirtyFlag_[8]=true;
        if(!pJson["project"].isNull() )
            project_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["project"].asInt64() ) );
    }
}

void Ticket::updateByMasqueradedJson(const Json::Value& pJson,
        const std::vector<std::string>& pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]) ) {
        if(!pJson[pMasqueradingVector[0]].isNull() )
            id_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[0]].asInt64() ) );
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]) ) {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull() )
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString() );
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]) ) {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull() )
            descr_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString() );
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]) ) {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull() )
            ticketStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString() );
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]) ) {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull() )
            severity_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString() );
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]) ) {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull() ) {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]) ) {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull() ) {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]) ) {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull() )
            assigned_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[7]].asInt64() ) );
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]) ) {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull() )
            project_=std::make_shared<int32_t>( static_cast<int32_t>(pJson[pMasqueradingVector[8]].asInt64() ) );
    }
}

void Ticket::updateByJson(const Json::Value& pJson) noexcept(false)
{
    if(pJson.isMember("id") ) {
        if(!pJson["id"].isNull() )
            id_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["id"].asInt64() ) );
    }
    if(pJson.isMember("title") ) {
        dirtyFlag_[1] = true;
        if(!pJson["title"].isNull() )
            title_=std::make_shared<std::string>(pJson["title"].asString() );
    }
    if(pJson.isMember("descr") ) {
        dirtyFlag_[2] = true;
        if(!pJson["descr"].isNull() )
            descr_=std::make_shared<std::string>(pJson["descr"].asString() );
    }
    if(pJson.isMember("ticket_status") ) {
        dirtyFlag_[3] = true;
        if(!pJson["ticket_status"].isNull() )
            ticketStatus_=std::make_shared<std::string>(pJson["ticket_status"].asString() );
    }
    if(pJson.isMember("severity") ) {
        dirtyFlag_[4] = true;
        if(!pJson["severity"].isNull() )
            severity_=std::make_shared<std::string>(pJson["severity"].asString() );
    }
    if(pJson.isMember("created_date") ) {
        dirtyFlag_[5] = true;
        if(!pJson["created_date"].isNull() ) {
            auto timeStr = pJson["created_date"].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                createdDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("resolved_date") ) {
        dirtyFlag_[6] = true;
        if(!pJson["resolved_date"].isNull() ) {
            auto timeStr = pJson["resolved_date"].asString();
            struct tm stm{};
            memset(&stm, 0, sizeof(stm) );
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p) {
                if(*p=='.') {
                    std::string decimals(p+1, &timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                        decimals += "0";
                    decimalNum = static_cast<size_t>(atol(decimals.c_str() ) );
                }
                resolvedDate_=std::make_shared<trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("assigned") ) {
        dirtyFlag_[7] = true;
        if(!pJson["assigned"].isNull() )
            assigned_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["assigned"].asInt64() ) );
    }
    if(pJson.isMember("project") ) {
        dirtyFlag_[8] = true;
        if(!pJson["project"].isNull() )
            project_=std::make_shared<int32_t>( static_cast<int32_t>(pJson["project"].asInt64() ) );
    }
}

const int32_t& Ticket::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}

const std::shared_ptr<int32_t>& Ticket::getId() const noexcept
{
    return id_;
}

void Ticket::setId(const int32_t& pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Ticket::PrimaryKeyType& Ticket::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string& Ticket::getValueOfTitle() const noexcept
{
    const static std::string defaultValue = std::string();
    if(title_)
        return *title_;
    return defaultValue;
}

const std::shared_ptr<std::string>& Ticket::getTitle() const noexcept
{
    return title_;
}

void Ticket::setTitle(const std::string& pTitle) noexcept
{
    title_ = std::make_shared<std::string>(pTitle);
    dirtyFlag_[1] = true;
}

void Ticket::setTitle(std::string&& pTitle) noexcept
{
    title_ = std::make_shared<std::string>(std::move(pTitle) );
    dirtyFlag_[1] = true;
}

const std::string& Ticket::getValueOfDescr() const noexcept
{
    const static std::string defaultValue = std::string();
    if(descr_)
        return *descr_;
    return defaultValue;
}

const std::shared_ptr<std::string>& Ticket::getDescr() const noexcept
{
    return descr_;
}

void Ticket::setDescr(const std::string& pDescr) noexcept
{
    descr_ = std::make_shared<std::string>(pDescr);
    dirtyFlag_[2] = true;
}

void Ticket::setDescr(std::string&& pDescr) noexcept
{
    descr_ = std::make_shared<std::string>(std::move(pDescr) );
    dirtyFlag_[2] = true;
}

const std::string& Ticket::getValueOfTicketStatus() const noexcept
{
    const static std::string defaultValue = std::string();
    if(ticketStatus_)
        return *ticketStatus_;
    return defaultValue;
}

const std::shared_ptr<std::string>& Ticket::getTicketStatus() const noexcept
{
    return ticketStatus_;
}

void Ticket::setTicketStatus(const std::string& pTicketStatus) noexcept
{
    ticketStatus_ = std::make_shared<std::string>(pTicketStatus);
    dirtyFlag_[3] = true;
}

void Ticket::setTicketStatus(std::string&& pTicketStatus) noexcept
{
    ticketStatus_ = std::make_shared<std::string>(std::move(pTicketStatus) );
    dirtyFlag_[3] = true;
}

const std::string& Ticket::getValueOfSeverity() const noexcept
{
    const static std::string defaultValue = std::string();
    if(severity_)
        return *severity_;
    return defaultValue;
}

const std::shared_ptr<std::string>& Ticket::getSeverity() const noexcept
{
    return severity_;
}

void Ticket::setSeverity(const std::string& pSeverity) noexcept
{
    severity_ = std::make_shared<std::string>(pSeverity);
    dirtyFlag_[4] = true;
}

void Ticket::setSeverity(std::string&& pSeverity) noexcept
{
    severity_ = std::make_shared<std::string>(std::move(pSeverity) );
    dirtyFlag_[4] = true;
}

const trantor::Date& Ticket::getValueOfCreatedDate() const noexcept
{
    const static trantor::Date defaultValue = trantor::Date();
    if(createdDate_)
        return *createdDate_;
    return defaultValue;
}

const std::shared_ptr<trantor::Date>& Ticket::getCreatedDate() const noexcept
{
    return createdDate_;
}

void Ticket::setCreatedDate(const trantor::Date& pCreatedDate) noexcept
{
    createdDate_ = std::make_shared<trantor::Date>(pCreatedDate);
    dirtyFlag_[5] = true;
}

const trantor::Date& Ticket::getValueOfResolvedDate() const noexcept
{
    const static trantor::Date defaultValue = trantor::Date();
    if(resolvedDate_)
        return *resolvedDate_;
    return defaultValue;
}

const std::shared_ptr<trantor::Date>& Ticket::getResolvedDate() const noexcept
{
    return resolvedDate_;
}

void Ticket::setResolvedDate(const trantor::Date& pResolvedDate) noexcept
{
    resolvedDate_ = std::make_shared<trantor::Date>(pResolvedDate);
    dirtyFlag_[6] = true;
}

void Ticket::setResolvedDateToNull() noexcept
{
    resolvedDate_.reset();
    dirtyFlag_[6] = true;
}

const int32_t& Ticket::getValueOfAssigned() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(assigned_)
        return *assigned_;
    return defaultValue;
}

const std::shared_ptr<int32_t>& Ticket::getAssigned() const noexcept
{
    return assigned_;
}

void Ticket::setAssigned(const int32_t& pAssigned) noexcept
{
    assigned_ = std::make_shared<int32_t>(pAssigned);
    dirtyFlag_[7] = true;
}

void Ticket::setAssignedToNull() noexcept
{
    assigned_.reset();
    dirtyFlag_[7] = true;
}

const int32_t& Ticket::getValueOfProject() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(project_)
        return *project_;
    return defaultValue;
}

const std::shared_ptr<int32_t>& Ticket::getProject() const noexcept
{
    return project_;
}

void Ticket::setProject(const int32_t& pProject) noexcept
{
    project_ = std::make_shared<int32_t>(pProject);
    dirtyFlag_[8] = true;
}

void Ticket::updateId(const uint64_t id)
{}

const std::vector<std::string>& Ticket::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "title",
        "descr",
        "ticket_status",
        "severity",
        "created_date",
        "resolved_date",
        "assigned",
        "project"
    };
    return inCols;
}

void Ticket::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if(dirtyFlag_[1]) {
        if(getTitle() )
            binder << getValueOfTitle();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[2]) {
        if(getDescr() )
            binder << getValueOfDescr();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[3]) {
        if(getTicketStatus() )
            binder << getValueOfTicketStatus();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[4]) {
        if(getSeverity() )
            binder << getValueOfSeverity();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[5]) {
        if(getCreatedDate() )
            binder << getValueOfCreatedDate();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[6]) {
        if(getResolvedDate() )
            binder << getValueOfResolvedDate();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[7]) {
        if(getAssigned() )
            binder << getValueOfAssigned();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[8]) {
        if(getProject() )
            binder << getValueOfProject();
        else
            binder << nullptr;
    }
}

const std::vector<std::string> Ticket::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
        ret.push_back(getColumnName(1) );
    if(dirtyFlag_[2])
        ret.push_back(getColumnName(2) );
    if(dirtyFlag_[3])
        ret.push_back(getColumnName(3) );
    if(dirtyFlag_[4])
        ret.push_back(getColumnName(4) );
    if(dirtyFlag_[5])
        ret.push_back(getColumnName(5) );
    if(dirtyFlag_[6])
        ret.push_back(getColumnName(6) );
    if(dirtyFlag_[7])
        ret.push_back(getColumnName(7) );
    if(dirtyFlag_[8])
        ret.push_back(getColumnName(8) );
    return ret;
}

void Ticket::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
    if(dirtyFlag_[1]) {
        if(getTitle() )
            binder << getValueOfTitle();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[2]) {
        if(getDescr() )
            binder << getValueOfDescr();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[3]) {
        if(getTicketStatus() )
            binder << getValueOfTicketStatus();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[4]) {
        if(getSeverity() )
            binder << getValueOfSeverity();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[5]) {
        if(getCreatedDate() )
            binder << getValueOfCreatedDate();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[6]) {
        if(getResolvedDate() )
            binder << getValueOfResolvedDate();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[7]) {
        if(getAssigned() )
            binder << getValueOfAssigned();
        else
            binder << nullptr;
    }
    if(dirtyFlag_[8]) {
        if(getProject() )
            binder << getValueOfProject();
        else
            binder << nullptr;
    }
}

Json::Value Ticket::toJson() const
{
    Json::Value ret;
    if(getId() )
        ret["id"]=getValueOfId();
    else
        ret["id"]=Json::Value();
    if(getTitle() )
        ret["title"]=getValueOfTitle();
    else
        ret["title"]=Json::Value();
    if(getDescr() )
        ret["descr"]=getValueOfDescr();
    else
        ret["descr"]=Json::Value();
    if(getTicketStatus() )
        ret["ticket_status"]=getValueOfTicketStatus();
    else
        ret["ticket_status"]=Json::Value();
    if(getSeverity() )
        ret["severity"]=getValueOfSeverity();
    else
        ret["severity"]=Json::Value();
    if(getCreatedDate() )
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    else
        ret["created_date"]=Json::Value();
    if(getResolvedDate() )
        ret["resolved_date"]=getResolvedDate()->toDbStringLocal();
    else
        ret["resolved_date"]=Json::Value();
    if(getAssigned() )
        ret["assigned"]=getValueOfAssigned();
    else
        ret["assigned"]=Json::Value();
    if(getProject() )
        ret["project"]=getValueOfProject();
    else
        ret["project"]=Json::Value();
    return ret;
}

Json::Value Ticket::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9) {
        if(!pMasqueradingVector[0].empty() ) {
            if(getId() )
                ret[pMasqueradingVector[0]]=getValueOfId();
            else
                ret[pMasqueradingVector[0]]=Json::Value();
        }
        if(!pMasqueradingVector[1].empty() ) {
            if(getTitle() )
                ret[pMasqueradingVector[1]]=getValueOfTitle();
            else
                ret[pMasqueradingVector[1]]=Json::Value();
        }
        if(!pMasqueradingVector[2].empty() ) {
            if(getDescr() )
                ret[pMasqueradingVector[2]]=getValueOfDescr();
            else
                ret[pMasqueradingVector[2]]=Json::Value();
        }
        if(!pMasqueradingVector[3].empty() ) {
            if(getTicketStatus() )
                ret[pMasqueradingVector[3]]=getValueOfTicketStatus();
            else
                ret[pMasqueradingVector[3]]=Json::Value();
        }
        if(!pMasqueradingVector[4].empty() ) {
            if(getSeverity() )
                ret[pMasqueradingVector[4]]=getValueOfSeverity();
            else
                ret[pMasqueradingVector[4]]=Json::Value();
        }
        if(!pMasqueradingVector[5].empty() ) {
            if(getCreatedDate() )
                ret[pMasqueradingVector[5]]=getCreatedDate()->toDbStringLocal();
            else
                ret[pMasqueradingVector[5]]=Json::Value();
        }
        if(!pMasqueradingVector[6].empty() ) {
            if(getResolvedDate() )
                ret[pMasqueradingVector[6]]=getResolvedDate()->toDbStringLocal();
            else
                ret[pMasqueradingVector[6]]=Json::Value();
        }
        if(!pMasqueradingVector[7].empty() ) {
            if(getAssigned() )
                ret[pMasqueradingVector[7]]=getValueOfAssigned();
            else
                ret[pMasqueradingVector[7]]=Json::Value();
        }
        if(!pMasqueradingVector[8].empty() ) {
            if(getProject() )
                ret[pMasqueradingVector[8]]=getValueOfProject();
            else
                ret[pMasqueradingVector[8]]=Json::Value();
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId() )
        ret["id"]=getValueOfId();
    else
        ret["id"]=Json::Value();
    if(getTitle() )
        ret["title"]=getValueOfTitle();
    else
        ret["title"]=Json::Value();
    if(getDescr() )
        ret["descr"]=getValueOfDescr();
    else
        ret["descr"]=Json::Value();
    if(getTicketStatus() )
        ret["ticket_status"]=getValueOfTicketStatus();
    else
        ret["ticket_status"]=Json::Value();
    if(getSeverity() )
        ret["severity"]=getValueOfSeverity();
    else
        ret["severity"]=Json::Value();
    if(getCreatedDate() )
        ret["created_date"]=getCreatedDate()->toDbStringLocal();
    else
        ret["created_date"]=Json::Value();
    if(getResolvedDate() )
        ret["resolved_date"]=getResolvedDate()->toDbStringLocal();
    else
        ret["resolved_date"]=Json::Value();
    if(getAssigned() )
        ret["assigned"]=getValueOfAssigned();
    else
        ret["assigned"]=Json::Value();
    if(getProject() )
        ret["project"]=getValueOfProject();
    else
        ret["project"]=Json::Value();
    return ret;
}

bool Ticket::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
    if(pJson.isMember("id") ) {
        if(!validJsonOfField(0, "id", pJson["id"], err, true) )
            return false;
    }
    if(pJson.isMember("title") ) {
        if(!validJsonOfField(1, "title", pJson["title"], err, true) )
            return false;
    } else {
        err="The title column cannot be null";
        return false;
    }
    if(pJson.isMember("descr") ) {
        if(!validJsonOfField(2, "descr", pJson["descr"], err, true) )
            return false;
    } else {
        err="The descr column cannot be null";
        return false;
    }
    if(pJson.isMember("ticket_status") ) {
        if(!validJsonOfField(3, "ticket_status", pJson["ticket_status"], err, true) )
            return false;
    } else {
        err="The ticket_status column cannot be null";
        return false;
    }
    if(pJson.isMember("severity") ) {
        if(!validJsonOfField(4, "severity", pJson["severity"], err, true) )
            return false;
    } else {
        err="The severity column cannot be null";
        return false;
    }
    if(pJson.isMember("created_date") ) {
        if(!validJsonOfField(5, "created_date", pJson["created_date"], err, true) )
            return false;
    } else {
        err="The created_date column cannot be null";
        return false;
    }
    if(pJson.isMember("resolved_date") ) {
        if(!validJsonOfField(6, "resolved_date", pJson["resolved_date"], err, true) )
            return false;
    }
    if(pJson.isMember("assigned") ) {
        if(!validJsonOfField(7, "assigned", pJson["assigned"], err, true) )
            return false;
    }
    if(pJson.isMember("project") ) {
        if(!validJsonOfField(8, "project", pJson["project"], err, true) )
            return false;
    } else {
        err="The project column cannot be null";
        return false;
    }
    return true;
}

bool Ticket::validateMasqueradedJsonForCreation(const Json::Value& pJson,
        const std::vector<std::string>& pMasqueradingVector,
        std::string& err)
{
    if(pMasqueradingVector.size() != 9) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if(!pMasqueradingVector[0].empty() ) {
            if(pJson.isMember(pMasqueradingVector[0]) ) {
                if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true) )
                    return false;
            }
        }
        if(!pMasqueradingVector[1].empty() ) {
            if(pJson.isMember(pMasqueradingVector[1]) ) {
                if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if(!pMasqueradingVector[2].empty() ) {
            if(pJson.isMember(pMasqueradingVector[2]) ) {
                if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[2] + " column cannot be null";
                return false;
            }
        }
        if(!pMasqueradingVector[3].empty() ) {
            if(pJson.isMember(pMasqueradingVector[3]) ) {
                if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[3] + " column cannot be null";
                return false;
            }
        }
        if(!pMasqueradingVector[4].empty() ) {
            if(pJson.isMember(pMasqueradingVector[4]) ) {
                if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[4] + " column cannot be null";
                return false;
            }
        }
        if(!pMasqueradingVector[5].empty() ) {
            if(pJson.isMember(pMasqueradingVector[5]) ) {
                if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[5] + " column cannot be null";
                return false;
            }
        }
        if(!pMasqueradingVector[6].empty() ) {
            if(pJson.isMember(pMasqueradingVector[6]) ) {
                if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true) )
                    return false;
            }
        }
        if(!pMasqueradingVector[7].empty() ) {
            if(pJson.isMember(pMasqueradingVector[7]) ) {
                if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true) )
                    return false;
            }
        }
        if(!pMasqueradingVector[8].empty() ) {
            if(pJson.isMember(pMasqueradingVector[8]) ) {
                if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true) )
                    return false;
            } else {
                err="The " + pMasqueradingVector[8] + " column cannot be null";
                return false;
            }
        }
    }catch(const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}

bool Ticket::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
    if(pJson.isMember("id") ) {
        if(!validJsonOfField(0, "id", pJson["id"], err, false) )
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("title") ) {
        if(!validJsonOfField(1, "title", pJson["title"], err, false) )
            return false;
    }
    if(pJson.isMember("descr") ) {
        if(!validJsonOfField(2, "descr", pJson["descr"], err, false) )
            return false;
    }
    if(pJson.isMember("ticket_status") ) {
        if(!validJsonOfField(3, "ticket_status", pJson["ticket_status"], err, false) )
            return false;
    }
    if(pJson.isMember("severity") ) {
        if(!validJsonOfField(4, "severity", pJson["severity"], err, false) )
            return false;
    }
    if(pJson.isMember("created_date") ) {
        if(!validJsonOfField(5, "created_date", pJson["created_date"], err, false) )
            return false;
    }
    if(pJson.isMember("resolved_date") ) {
        if(!validJsonOfField(6, "resolved_date", pJson["resolved_date"], err, false) )
            return false;
    }
    if(pJson.isMember("assigned") ) {
        if(!validJsonOfField(7, "assigned", pJson["assigned"], err, false) )
            return false;
    }
    if(pJson.isMember("project") ) {
        if(!validJsonOfField(8, "project", pJson["project"], err, false) )
            return false;
    }
    return true;
}

bool Ticket::validateMasqueradedJsonForUpdate(const Json::Value& pJson,
        const std::vector<std::string>& pMasqueradingVector,
        std::string& err)
{
    if(pMasqueradingVector.size() != 9) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]) ) {
            if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false) )
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]) ) {
            if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]) ) {
            if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]) ) {
            if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]) ) {
            if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]) ) {
            if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]) ) {
            if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]) ) {
            if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false) )
                return false;
        }
        if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]) ) {
            if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false) )
                return false;
        }
    }catch(const Json::LogicError& e)
    {
        err = e.what();
        return false;
    }
    return true;
}

bool Ticket::validJsonOfField(size_t index,
        const std::string& fieldName,
        const Json::Value& pJson,
        std::string& err,
        bool isForCreation)
{
    switch(index) {
    case 0:
        if(pJson.isNull() ) {
            err="The " + fieldName + " column cannot be null";
            return false;
        }
        if(isForCreation) {
            err="The automatic primary key cannot be set";
            return false;
        }
        if(!pJson.isInt() ) {
            err="Type error in the "+fieldName+" field";
            return false;
        }
        break;
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
        if(pJson.isNull() ) {
            err="The " + fieldName + " column cannot be null";
            return false;
        }
        if(!pJson.isString() ) {
            err="Type error in the "+fieldName+" field";
            return false;
        }
        break;
    case 6:
        if(pJson.isNull() )
            return true;
        if(!pJson.isString() ) {
            err="Type error in the "+fieldName+" field";
            return false;
        }
        break;
    case 7:
        if(pJson.isNull() )
            return true;
        if(!pJson.isInt() ) {
            err="Type error in the "+fieldName+" field";
            return false;
        }
        break;
    case 8:
        if(pJson.isNull() ) {
            err="The " + fieldName + " column cannot be null";
            return false;
        }
        if(!pJson.isInt() ) {
            err="Type error in the "+fieldName+" field";
            return false;
        }
        break;

    default:
        err="Internal error in the server";
        return false;
        break;
    }
    return true;
}
